POST http://localhost:3000/authenticateUser
Content-Type: application/json

{
    "name": "fulano007",
    "password": "1234"
}

###

POST http://localhost:3000/createAcount
Content-Type: application/json

{
    "name": "fulano007",
    "password": "1234",
    "email": "fulano@doido.com"
}

###

POST http://localhost:3000/api/list
Content-Type: application/json

{
    "list": {"name": "lista1"}
}

###

GET  http://localhost:3000/api/list


###

POST http://localhost:3000/api/list
Content-Type: application/json

{
    "list": { "name": "lista1"}
}

###
GET http://localhost:3000/api/task/lista1


###

POST http://localhost:3000/api/task
Content-Type: application/json

{
    "listName": "lista1",
    "task": {"name": "tarefa3", "responsible": "fulano", "finalDate": "05/01/21", "state": "completada", "pos": 1}
}

###
PUT  http://localhost:3000/api/list
Content-Type: application/json

{
    "userName": "fulano",
    "listName": "listaTeste1",
    "newListName": "lista1"
}

###
PUT http://localhost:3000/api/task
Content-Type: application/json

{
    "listName": "lista5",
    "control": {"oldName": "tarefa3", "oldState": "normal"},
    "task": {"name": "tarefa3", "responsible": "fulano", "finalDate": "05/01/21", "state": "completada", "pos": 2}
}

###

DELETE   http://localhost:3000/api/task
Content-Type: application/json

{
    "listName": "lista1",
    "taskName": "tarefa3"
}

###
DELETE   http://localhost:3000/api/list
Content-Type: application/json

{
    "userName": "fulano",
    "listName": "lista1",
    "state": "normal"
}