POST http://localhost:3000/api/list
Content-Type: application/json

{
    "userName": "fulano",
    "list": {"name": "lista2"}
}

###

POST http://localhost:3000/createAcount
Content-Type: application/json

{
    "name": "fulano",
    "password": "123",
    "email": "fulano@doido.com"
}

###

GET  http://localhost:3000/api/list
Content-Type: application/json

{
    "userName": "fulano"
}
###
GET http://localhost:3000/api/task
Content-type: application/json

{
    "userName": "fulano",
    "listName": "lista1"
}


###

POST http://localhost:3000/api/task
Content-Type: application/json

{
    "userName": "fulano",
    "listName": "lista1",
    "task": {"name": "tarefa2", "responsible": "fulano", "finalDate": "05/01/21", "state": "andamento"}
}

###
PUT  http://localhost:3000/api/list
Content-Type: application/json

{
    "userName": "fulano",
    "listName": "listaTeste1",
    "newListName": "lista1"
}

###
DELETE   http://localhost:3000/api/list
Content-Type: application/json

{
    "userName": "fulano",
    "listName": "lista1"
}