POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "Fulano",
    "password": "1234"
}

###

POST http://localhost:4000/createAcount
Content-Type: application/json

{
    "name": "Fulano",
    "password": "1234"
}